Contadores/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('apps.usuario.urls')), 
    re_path('', include('apps.home.urls')), 
    path('', include('apps.medidor.urls')),   
   
      


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   

apps/usuario/urls.py
from django.urls import path
from . import views 
              
app_name = "users_app"  
 
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register',), 
    path('login/', views.LoginUser.as_view(), name='user_login',), 
    path('logout/', views.LogoutView.as_view(), name='user_logout',), 
    path('update/', views.UpdatePasswordView.as_view(), name='user_update',), 
    path('user-verification/<pk>/', views.CodeVerificationView.as_view(), name='user-verification',), 
    path('usuarios/', views.UserListView.as_view(), name='usuarios',), 
    path('editar_usuarios/<pk>/', views.UserUpdateView.as_view(), name='editar_usuarios',), 
    path('eliminar_usuarios/<pk>/', views.UserDelete.as_view(), name='eliminar_usuarios',), 

]       
  

apps/usuario/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):

    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otros'), 
    )

    username = models.CharField(max_length=10, unique=True)
    email = models.EmailField()
    nombres = models.CharField(max_length=30)
    apellidos = models.CharField(max_length=30)
    genero = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    codregistro = models.CharField(max_length=6, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)


    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = ['email',]

    objects = UserManager()

    def get_short_name(self):
        return self.username
    
    def get_full_name(self):
        return self.nombres + ' ' + self.apellidos

apps/usuario/forms.py
from django import forms
from django.contrib.auth import authenticate


from .models import User

class UserRegisterForm(forms.ModelForm):

    password1 = forms.CharField(
        label = 'Contraseña',
        required = True, 
        widget = forms.PasswordInput(
           attrs={
               'placeholder':'Contraseña'
           }
        )
    )

    password2 = forms.CharField(
        label = 'Contraseña',
        required = True, 
        widget = forms.PasswordInput(
           attrs={
               'placeholder':'Repetir Contraseña'
           }
        )
    )

    class Meta:
        model = User
        fields = ('username',
                  'email',
                  'nombres',
                  'apellidos',
                  'genero',
                  )

 
    # Validando los forms

    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error('password2', 'Las contraseñas no son iguales')

    # Implementar que una contraseña no sea menor q 5 digitos 


class LoginForm(forms.Form):
    username = forms.CharField(
        label = 'username',
        required = True, 
        widget = forms.TextInput(
           attrs={
               'placeholder':'username',
               'style': '{ margin : 10px}',
           }
        )
    )
 
    password = forms.CharField(
        label = 'Contraseña',
        required = True, 
        widget = forms.PasswordInput(
           attrs={
               'placeholder':'Contraseña'
           }
        )
    )

    # Validando los 2 campos
    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        if not authenticate(username=username, password=password):
            raise forms.ValidationError('Los datos de usuario no son correctos')
        
        return self.cleaned_data
    
    

class UpdatePasswordForm(forms.Form):

    password1 = forms.CharField(
        label = 'Contraseña',
        required = True, 
        widget = forms.PasswordInput(
           attrs={
               'placeholder':'Contraseña Actual'
           }
        )
    )

    password2 = forms.CharField(
        label = 'Contraseña',
        required = True, 
        widget = forms.PasswordInput(
           attrs={
               'placeholder':'Contraseña Nueva'
           }
        )
    )


class VerificationForm(forms.Form):
    codregistro = forms.CharField(required=True)

    def __init__(self, pk, *args, **kwargs):
        self.id_user = pk
        super(VerificationForm, self).__init__(*args, **kwargs)


    def clean_codregistro(self):
        codigo = self.cleaned_data['codregistro']

        if len(codigo) == 6:
            #  verificando si el id del usuario y el codigo son validos
            activo = User.objects.cod_validation(
                self.id_user,
                codigo
            ) 
            if not activo:
                raise forms.ValidationError('el codigo es incorrecto')

        else:
            raise forms.ValidationError('el codigo es incorrecto')
        
 
# Formulario Usuario

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'nombres', 'apellidos', 'genero', 'codregistro', 'is_staff', 'is_active']

apps/usuario/views.py
from django.core.mail import send_mail
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    View, ListView, UpdateView, DeleteView
)
from django.views.generic.edit import (
    FormView
)

from .forms import (UserRegisterForm, LoginForm,
                    UpdatePasswordForm, VerificationForm, UserUpdateForm)
from .functions import code_generator
from .models import User
 

# Create your views here.


class UserRegisterView(FormView):
    template_name = 'usuario/register.html'
    form_class = UserRegisterForm
    success_url = '/' 

    def form_valid(self, form):
        # Generando el Codigo
        codigo = code_generator()


        usuario = User.objects.create_user(
            form.cleaned_data['username'],
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            nombres = form.cleaned_data['nombres'],
            apellidos = form.cleaned_data['apellidos'],
            genero = form.cleaned_data['genero'],
            codregistro = codigo

        )

        # Enviar el codigo al email del usuario
        asunto = 'Confirmación de Email'
        mensaje = 'Código de Verificación: ' + codigo
        email_remitente = 'mdrvacar@gmail.com'

        send_mail(asunto, mensaje, email_remitente, [form.cleaned_data['email'],])
        # Redirigir a pantalla de verificación.
        return HttpResponseRedirect(
            reverse(
                'users_app:user-verification',
                kwargs={'pk': usuario.id}
            )
        )


class LoginUser(FormView):
    template_name = "usuario/login.html"
    form_class = LoginForm
    success_url = reverse_lazy('entrar')

    def form_valid(self, form): 
        # Verificar el LOGIN
        user= authenticate(
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password']
        )
        # Haciendo el Login
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):

    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user_login'
            )
    )


class UpdatePasswordView(LoginRequiredMixin, FormView):
    template_name = "usuario/update.html"
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_app:user_login')
    login_url = reverse_lazy('users_app:user_login')

    def form_valid(self, form):
        usuario = self.request.user
        user= authenticate(
            username = usuario.username,
            password = form.cleaned_data['password1']
        )

        if user:
            new_password = form.cleaned_data['password2']
            usuario.set_password(new_password)
            usuario.save()

        logout(self.request)
        return super(UpdatePasswordView, self).form_valid(form)




class CodeVerificationView(FormView):
    template_name = "usuario/verification.html"
    form_class = VerificationForm
    success_url = reverse_lazy('users_app:user_login')

    def get_form_kwargs(self):
        kwargs = super(CodeVerificationView, self).get_form_kwargs()
        kwargs.update({
            'pk': self.kwargs['pk'],
        })
        return kwargs

    def form_valid(self, form):
        User.objects.filter(
            id=self.kwargs['pk']
        ).update(
            is_active = True
        )
       
       
        return super(CodeVerificationView, self).form_valid(form)


# Usuarios

class UserListView(ListView):
    model = User
    template_name = 'usuario/user_list.html'
    context_object_name = 'usuarios'
    paginate_by = 7 # Paginación


  
class UserUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'usuario/user_update.html'
    success_url = reverse_lazy('users_app:usuarios')

    def form_valid(self, form):
        response = super().form_valid(form)
        # Configura el mensaje de éxito
        messages.success(self.request, 'Actualizado con éxito')
        return response



class UserDelete(DeleteView):
    model = User
    template_name = "usuario/delete_user.html"
    context_object_name = 'object'
    success_url = reverse_lazy('users_app:usuarios')

    def delete(self, request, *args, **kwargs):
        # Elimina el objeto
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        # Configura el mensaje de éxito
        messages.success(self.request, 'Eliminado con éxito')
        return HttpResponseRedirect(success_url)
    






   

    

templates/usuario/delete_user.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'include/header.html' %}

<div class="grid-container"> 
    <div class="grid-x ">
        <h3 class="cell">Eliminar Usuario "{{ object.username}}" </h3>
        <form class="cell " method="post">{% csrf_token %}
        
            <div class="callout secondary">
                <h5>Desea eliminar este usuario?</h5>
                <button type="submit" class="alert button">Confirmar</button>
            </div>        
        </form>
    </div>
</div>

{% endblock content %}   

templates/usuario/login.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">

{% block content %} 

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell medium-6 large-4" style="margin-top: 2em;">
        <div class="card" style="width: 100%;">
            <div class="card-divider">
                <h4>Acceso de Usuario</h4>
            </div>

            <div class="card-section">
                <form class="grid-x grid-margin-x" method="post" >{% csrf_token %}
                    <div class="cell medium-12">
                        <label>Usuario:
                            {{ form.username }}                           </label>
                    </div>

                    <div class="cell medium-12">
                        <label>Contraseña:
                            {{ form.password }}                         </label>
                    </div>

                    <button type="submit" class="cell hollow button primary">Acceder</button>
                    <a class="cell hallow button alert" href="{% url 'users_app:user_register' %}">Registrar</a>
                </form>
            </div>
        </div>
        </form>
    </div>
</div>

{% endblock content %} 

templates/usuario/register.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">

{% block content %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell medium-10 large-6" style="margin-top: 2em;">
            <div class="card" style="width: 100%;">
                <div class="card-divider">
                    <h4>Ingrese sus Datos</h4>
                </div>

                <div class="card-section">
                    <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
                       
                        <div class="cell large-12">
                            <label>Email:
                                {{ form.email }}
                            </label>
                        </div>

                        <div class="cell large-6">
                            <label>Usuario:
                                {{ form.username }}                            </label>
                        </div>

                        <div class="cell large-6">
                            <label>Nombre:
                                {{ form.nombres }}                            </label>
                        </div>

                        <div class="cell large-6">
                            <label>Apellidos:
                                {{ form.apellidos }}                            </label>
                        </div>

                        <div class="cell large-6"> 
                            <label>Genero:
                                {{ form.genero }}                            </label>
                        </div>

                        <div class="cell large-12">
                            <label>Contraseña:
                                {{ form.password1 }}
                            </label>
                        </div>

                        <div class="cell large-12">
                            <label>Repetir Contraseña:
                                {{ form.password2 }}                            </label>
                        </div>
                        <button type="submit" class="cell hallow button primary">Registrar</button>
                    </form>
                </div>

            </div>

        </div>
    </div>

</div>

{% endblock content %} 

templates/usuario/update.html
<!DOCTYPE html>
<html lang="en"> 
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Cambiar Contraseña: {{user.nombres}} </h1>
    <form  method="post">{% csrf_token %}
        {{form.as_p}}
        <button type="submit">Actualizar</button>
    </form>
</body>
</html>

templates/usuario/user_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'include/header.html' %}

<div class="grid-container">

    <div class="grid-x">
      <h1 class="cell">Lista Usuarios</h1>
        <div class="cell large-2">
        </div>
      </form>
    </div>
   
    <div class="grid-x">
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Género</th>
                        <th>¿Es personal de staff?</th>
                        <th>¿Está activo?</th>
                        <th>Acciones</th> 
                    </tr>
                </thead> 
                <tbody>
                    {% for user in  usuarios %}  
                        <tr>
                            <td>{{ user.username }}</td>
                            <td>{{ user.email }}</td> 
                            <td>{{ user.nombres }}</td>
                            <td>{{ user.apellidos }}</td>
                            <td>{{ user.genero }}</td>
                            <td>{{ user.is_staff }}</td>
                            <td>{{ user.is_active }}</td>
                            <td>
                                <a class="button success" href="{% url 'users_app:editar_usuarios' user.id %}"><i class="fa-solid fa-pencil fa-1x" alt="Editar"></i></a>
                                <a class="button alert" href="{% url 'users_app:eliminar_usuarios' user.id %}"><i class="fa-solid fa-trash fa-1x" alt="Eliminar"></i></a>
                            </td>
                        </tr>
                    {% endfor %}     
                </tbody>                 
            </table>
        </div>
    </div>

    <div>
        {% if is_paginated %}
        <nav aria-label="Pagination">
            <ul class="pagination text-center">
                {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{ page_obj.previous_page_number }}">Atrás</a>
                    </li>
                {% endif %}
                {% for pagina in paginator.page_range %}
                {% if pagina == page_obj.number %}
                <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                {% else %}
                <li class=""><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                {% endif %}
            {% endfor %}
            

                {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
</div>

{% endblock content %}

templates/usuario/user_update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'include/header.html' %}
 
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> 
            Modificar Usuario
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="cell large-6">
                    <label>Usuario:
                        {{form.username}}                    </label>
                  </div>

                  <div class="cell large-6">
                    <label>Email:
                        {{form.email}}                    </label>
                  </div>

                  <div class="cell large-6">
                    <label>Nombre:
                        {{form.nombres}}                    </label>
                  </div>

                  <div class="cell large-6">
                    <label>Apellidos:
                        {{form.apellidos}}                    </label>
                  </div>

                  <div class="cell large-6">
                    <label>Genero: 
                        {{form.genero}}                    </label>
                  </div>

                  <div class="cell large-6">   
                    <label>Staff:
                        {{form.is_staff}}                    </label>
                  </div>

                  <div class="cell large-6">   
                    <label>Activación:
                        {{form.is_active}}                    </label>
                  </div>


                  <div class="cell">
                    <button class="submit success button" type="submit">Guardar</button> 
                  </div>

            </form>
        </div>
    </div>
</div>   

{% endblock content %}  

templates/usuario/verification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <title>Document</title>
</head>
<body>
    <h3>Verificación de Email</h3>
    <h3>Ingrese el codigo de verificación:</h3>
    <form method="post">{% csrf_token %}
        {{form.as_p}}
        <button type="submit">Confirmar</button>
    </form>
</body>
</html>