Contadores/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('apps.usuario.urls')), 
    re_path('', include('apps.home.urls')), 
    path('', include('apps.medidor.urls')),   
   
      


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   

apps/usuario/urls.py
from django.urls import path
from . import views 
              
app_name = "users_app"  
 
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register',), 
    path('login/', views.LoginUser.as_view(), name='user_login',), 
    path('logout/', views.LogoutView.as_view(), name='user_logout',), 
    path('update/', views.UpdatePasswordView.as_view(), name='user_update',), 
    path('user-verification/<pk>/', views.CodeVerificationView.as_view(), name='user-verification',), 
    path('usuarios/', views.UserListView.as_view(), name='usuarios',), 
    path('editar_usuarios/<pk>/', views.UserUpdateView.as_view(), name='editar_usuarios',), 
    path('eliminar_usuarios/<pk>/', views.UserDelete.as_view(), name='eliminar_usuarios',), 

]       
  

apps/medidor/models.py
from django.db import models

# Create your models here.
 
class Empresa(models.Model):
    nombre_empresa = models.CharField("Empresa", max_length=100, unique=True)  # Cambié max_length a un valor más grande para admitir nombres más largos

    def __str__(self):
        return self.nombre_empresa
 

class Cruce(models.Model): 
    valor_agua = models.IntegerField()
    agua1 = models.IntegerField()
    agua2 = models.IntegerField() 
    bombero = models.IntegerField()
    valor_luz = models.IntegerField()
    valor_gas = models.IntegerField()
    #fecha_registro = models.DateTimeField('Fecha de Registro', auto_now_add=True)
    fecha_registro = models.DateField()
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, null=True, blank=True)

 
class Vacar(models.Model): 
    valor_agua = models.IntegerField() 
    valor_P1 = models.IntegerField() 
    valor_P2 = models.IntegerField()
    valor_P3 = models.IntegerField()
    valor_gas_derecho = models.IntegerField()
    valor_gas_izquierdo = models.IntegerField()
    valor_gas_casa = models.IntegerField()
    gas = models.IntegerField()
    fecha_registro = models.DateField()
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, null=True, blank=True)

templates/include/header.html
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
    <div class="title-bar-title">Menu</div>
  </div>
   
  <div class="top-bar" id="responsive-menu">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu style="background-color: rgb(33, 31, 31);">
        <li><a href="{% url 'entrar' %}" style="color: #fff;"><i class="fa-solid fa-house fa-2x" onmouseover="this.style.color='#f7d086'" onmouseout="this.style.color='#fff'"></i></a></li>
        <li><a href="{% url 'panel_control' %}" style="color: #fff;"><i class="fa-solid fa-screwdriver-wrench fa-2x" onmouseover="this.style.color='#f7d086'" onmouseout="this.style.color='#fff'"></i></a></li>
        <li>
            <li class="has-submenu">
              <a href="#0" style="color: #fff;"><i class="fa-solid fa-table-list fa-2x" onmouseover="this.style.color='#f7d086'" onmouseout="this.style.color='#fff'"></i></a>
              <ul class="submenu menu vertical" data-submenu style="background-color: rgb(33, 31, 31);">
                <li><a href="{% url 'vacar_list' %}" style="color: #fff;" onmouseover="this.style.color='#f7d086';" onmouseout="this.style.color='#fff';">Listado El Vacar</a></li> 
                <li><a href="{% url 'cruce_list' %}" style="color: #fff;" onmouseover="this.style.color='#f7d086';" onmouseout="this.style.color='#fff';">Listado El Cruce</a></li>
            </li>
          </ul>    
        </li>             
      </ul>
    </div>

    <b style="color: #fff;">{{user.nombres}}</b>

    <div class="top-bar-right">
      <ul class="dropdown menu" data-dropdown-menu style="background-color: rgb(33, 31, 31);">
        <li class="has-submenu">
          <a href="#0" style="color: #fff;"><i class="fa-solid fa-user fa-2x" onmouseover="this.style.color='#f7d086'" onmouseout="this.style.color='#fff'"></i></a>
          <ul class="submenu menu vertical" data-submenu style="background-color: rgb(33, 31, 31);">
            <li><a href="{% url 'users_app:usuarios' %}" style="color: #fff;" onmouseover="this.style.color='#f7d086';" onmouseout="this.style.color='#fff';">Usuarios</a></li>
            <li><a href="{% url 'users_app:user_logout' %}" style="color: #fff;" onmouseover="this.style.color='#f7d086';" onmouseout="this.style.color='#fff';">Salir</a></li>
          </ul>
        </li>
      </ul>
    </div>  


  </div>
  
 

  